import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ImageBackground, View } from 'react-native';
import { collectionApi, marketplaceApi } from '../shared/api/services';
import { useSession } from '../shared/api/session';
import { usePreferences } from '../shared/lib/preferences';
import { Button, Card, EmptyState, ErrorState, IconButton, LinkButton, LoadingSkeleton, Row, Screen, ScreenHeader, SectionHeader, Text } from '../shared/ui/core';
import { ObjectCard } from '../shared/ui/objects';
import { useTheme } from '../shared/ui/theme';
export function HomeScreen() {
  const { colors } = useTheme(); const session = useSession(s => s.session); const enabled = !!session?.user.emailVerified; const interests = usePreferences(s => s.categoryIds);
  const stats = useQuery({ queryKey: ['statistics', session?.user.id], queryFn: ({ signal }) => collectionApi.statistics(signal), enabled });
  const recent = useQuery({ queryKey: ['collection', session?.user.id, 'recent'], queryFn: ({ signal }) => collectionApi.list({ sort: 'recent' }, undefined, signal), enabled });
  const recommendedCategory = session?.user.categoryIds[0] ?? interests[0];
  const market = useQuery({ queryKey: ['marketplace', 'home', recommendedCategory], queryFn: ({ signal }) => marketplaceApi.list({ categoryId: recommendedCategory }, undefined, signal) });
  const nextAction = !session ? { title: 'Начните с первого предмета', body: 'Сфотографируйте находку или откройте каталог, чтобы создать свою первую историю.', button: 'Открыть AI', onPress: () => router.push('/scan') } : stats.data?.total === 0 ? { title: 'Добавьте первый предмет', body: 'Коллекция становится полезнее, когда у каждого предмета есть фото, характеристики и история.', button: 'Добавить предмет', onPress: () => router.push('/collection/create') } : stats.data?.activeRequests ? { title: 'Есть активные заявки', body: 'Проверьте ответы специалистов и продолжите работу с обращениями.', button: 'Открыть заявки', onPress: () => router.push('/requests') } : { title: 'Продолжайте коллекцию', body: 'Найдите новый предмет в marketplace или проверьте находку с помощью AI.', button: 'Открыть marketplace', onPress: () => router.push('/marketplace') };
  return <Screen><ScreenHeader title="Ваш кабинет" eyebrow="ANTIQUE AI" action={<IconButton name="user" label="Профиль" onPress={() => router.push('/profile')} />} /><Text color={colors.muted}>Добро пожаловать{session ? `, ${session.user.name || 'коллекционер'}` : ', коллекционер'}.</Text>
    <Card><Text variant="label">Следующий шаг</Text><Text variant="heading">{nextAction.title}</Text><Text color={colors.muted}>{nextAction.body}</Text><Button title={nextAction.button} variant="secondary" onPress={nextAction.onPress} /></Card>
    <ImageBackground source={require('../../assets/bukhara-hero.png')} imageStyle={{ borderRadius: 18 }} style={{ borderRadius: 18, overflow: 'hidden' }}><Card style={{ backgroundColor: '#10283dcc', borderColor: '#8BD2DE88', padding: 20, minHeight: 252, justifyContent: 'flex-end' }}><Text variant="label" color="#9DE1E8">БУХАРА · КОЛЛЕКЦИОНЕРСКОЕ БЮРО</Text><Text variant="title" color={colors.inverse}>Что хранит{ '\n' }ваш предмет?</Text><Text color="#E3F2F4">Сфотографируйте находку. Сравните её с каталогом и узнайте больше об истории.</Text><Button title="Определить предмет" icon="aperture" variant="secondary" onPress={() => router.push('/scan')} /></Card></ImageBackground>
    <Row style={{ flexWrap: 'wrap' }}><View style={{ flex: 1, minWidth: 130 }}><LinkButton href="/collection" title="Моя коллекция" icon="grid" /></View><View style={{ flex: 1, minWidth: 130 }}><LinkButton href="/catalog" title="Каталоги" icon="book-open" /></View><View style={{ flex: 1, minWidth: 130 }}><LinkButton href="/assistant" title="Спросить AI" icon="message-circle" /></View></Row>
    {enabled ? <><SectionHeader title="Ваша коллекция" action="Открыть" onPress={() => router.push('/collection')} />{stats.isPending ? <LoadingSkeleton /> : stats.isError ? <ErrorState error={stats.error} retry={() => void stats.refetch()} /> : <Row style={{ flexWrap: 'wrap' }}>{[{ label: 'предметов', value: stats.data.total }, { label: 'категорий', value: stats.data.categories }, { label: 'активных заявок', value: stats.data.activeRequests }].map(s => <Card key={s.label} style={{ flex: 1, minWidth: 110 }}><Text variant="title">{s.value}</Text><Text variant="caption" color={colors.muted}>{s.label}</Text></Card>)}</Row>}<SectionHeader title="Недавно добавлены" />{recent.isPending ? <LoadingSkeleton /> : recent.isError ? <ErrorState error={recent.error} retry={() => void recent.refetch()} /> : recent.data.items.length ? recent.data.items.slice(0, 3).map(item => <ObjectCard key={item.id} item={item} compact />) : <EmptyState title="Место для первой находки" description="Добавьте предмет вручную или начните со снимка." action="Добавить предмет" onPress={() => router.push('/collection/create')} />}</> : <Card><Text variant="heading">Коллекция начинается с вас</Text><Text color={colors.muted}>Сохраните находки, личные заметки и историю приобретений.</Text><LinkButton href="/auth/register" title="Создать аккаунт" /></Card>}
    <SectionHeader title="Marketplace" action="Смотреть" onPress={() => router.push('/marketplace')} />{market.isPending ? <LoadingSkeleton /> : market.isError ? <ErrorState error={market.error} retry={() => void market.refetch()} /> : market.data.items.length ? market.data.items.slice(0, 3).map(item => <ObjectCard key={item.id} item={item} market compact />) : <EmptyState icon="shopping-bag" title="Новые находки впереди" description="Здесь появятся предметы от коллекционеров и продавцов." />}
    <Card><Text variant="heading">Нужен взгляд специалиста?</Text><Text color={colors.muted}>Отправьте фотографии и описание для профессионального осмотра.</Text><LinkButton href="/requests/create-inspection" title="Заказать осмотр" icon="shield" /></Card>
  </Screen>;
}
