import { useMutation, useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { identificationApi, collectionApi } from '../shared/api/services';
import { queryClient } from '../shared/api/query';
import { AuthGate } from '../widgets/AuthGate';
import { Badge, Button, Card, EmptyState, ErrorState, InlineError, LinkButton, LoadingSkeleton, Screen, ScreenHeader, SectionHeader, Text } from '../shared/ui/core';
import { ImageGallery, SourceCard } from '../shared/ui/objects';
import { useTheme } from '../shared/ui/theme';
const stages: Record<string, string> = { queued: 'В очереди на определение', reading_image: 'Изучаем фотографии', searching_collection: 'Ищем в вашей коллекции', searching_catalog: 'Ищем в каталоге', comparing: 'Сравниваем похожие предметы', checking_sources: 'Проверяем источники' };
export function IdentificationScreen() { return <AuthGate><IdentificationContent /></AuthGate>; }
function IdentificationContent() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { colors } = useTheme();
  const query = useQuery({ queryKey: ['identification', id], queryFn: ({ signal }) => identificationApi.get(id, signal), refetchInterval: query => query.state.data && !['completed', 'failed'].includes(query.state.data.status) ? 2500 : false });
  const feedback = useMutation({ mutationFn: ({ candidateId, accepted }: { candidateId: string | null; accepted: boolean }) => identificationApi.feedback(id, candidateId, accepted), onSuccess: () => { void query.refetch(); } });
  const web = useMutation({ mutationFn: () => identificationApi.web(id), onSuccess: result => queryClient.setQueryData(['identification', id], result) });
  const save = useMutation({ mutationFn: (candidateId: string) => collectionApi.create({ identificationId: id, candidateId }, `identification-${id}-${candidateId}`), onSuccess: item => { void queryClient.invalidateQueries({ queryKey: ['collection'] }); router.push({ pathname: '/collection/[id]', params: { id: item.id } }); } });
  if (query.isPending) return <Screen><LoadingSkeleton /></Screen>;
  if (query.isError) return <Screen><ErrorState error={query.error} retry={() => void query.refetch()} /></Screen>;
  const result = query.data;
  return <Screen><ScreenHeader title="Результат определения" eyebrow="AI · ВОЗМОЖНЫЕ СОВПАДЕНИЯ" back />{!['completed', 'failed'].includes(result.status) ? <Card><Badge label="АНАЛИЗ В ПРОЦЕССЕ" /><Text variant="heading" accessibilityLiveRegion="polite">{stages[result.status]}</Text><Text color={colors.muted}>Можно вернуться позже — результат будет сохранён.</Text><LoadingSkeleton /></Card> : result.status === 'failed' ? <EmptyState icon="help-circle" title="Не удалось определить" description={result.error || 'Попробуйте более чёткие фотографии или добавьте описание.'} action="Новый снимок" onPress={() => router.push('/scan')} /> : <><Text color={colors.muted}>Это предположение по видимым признакам, а не заключение о подлинности или пробе.</Text>{result.candidates.length ? result.candidates.map(candidate => <Card key={candidate.id}><ImageGallery photos={candidate.item.photos} /><Badge label={`${Math.round(candidate.confidence * 100)}% · ${candidate.origin === 'web' ? 'Внешние источники' : candidate.origin === 'catalog' ? 'Каталог' : 'Ваша коллекция'}`} /><Text variant="title">{candidate.item.title}</Text>{candidate.reasons.map(reason => <Text key={reason}>✓ {reason}</Text>)}{candidate.discrepancies.map(reason => <Text key={reason} color={colors.accent}>Требует уточнения: {reason}</Text>)}<Button title="Это мой предмет" loading={feedback.isPending} onPress={() => feedback.mutate({ candidateId: candidate.id, accepted: true })} /><Button title="Сохранить в коллекцию" loading={save.isPending} variant="secondary" onPress={() => save.mutate(candidate.id)} /><Button title="Не совпадает" variant="ghost" onPress={() => feedback.mutate({ candidateId: candidate.id, accepted: false })} /></Card>) : <EmptyState title="Уверенного совпадения нет" description="Добавьте другой ракурс или разрешите поиск по внешним источникам." />}<Button title="Ни один вариант не подходит" variant="ghost" disabled={feedback.isPending} onPress={() => feedback.mutate({ candidateId: null, accepted: false })} />{feedback.isSuccess ? <Text>Ваш ответ сохранён. Каталог не изменён.</Text> : null}<LinkButton href="/scan" title="Загрузить более чёткие фото" /><LinkButton href="/collection/create" title="Описать предмет вручную" />{result.canSearchWeb ? <Button title="Искать в интернете" loading={web.isPending} onPress={() => web.mutate()} /> : null}<LinkButton href="/requests/create-inspection" title="Заказать профессиональный осмотр" icon="shield" /></>}<InlineError error={feedback.error || web.error || save.error} />{result.sources.length ? <><SectionHeader title="Источники" />{result.sources.map(s => <SourceCard key={s.url} source={s} />)}</> : null}</Screen>;
}
