import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ImageBackground, View } from 'react-native';
import Animated, { FadeIn, ReduceMotion } from 'react-native-reanimated';
import { catalogApi } from '../shared/api/services';
import { usePreferences } from '../shared/lib/preferences';
import { Button, Card, Chip, ErrorState, Icon, LoadingSkeleton, Row, Screen, Text } from '../shared/ui/core';
import { useTheme } from '../shared/ui/theme';
export function OnboardingScreen() {
  const { colors } = useTheme(); const [step, setStep] = useState(0); const [ids, setIds] = useState<string[]>([]);
  const categories = useQuery({ queryKey: ['categories'], queryFn: ({ signal }) => catalogApi.categories(signal), enabled: step === 1 });
  const finish = () => { usePreferences.getState().finishOnboarding(ids); router.replace('/home'); };
  return <Screen><Row style={{ justifyContent: 'space-between' }}><Text variant="label" color={colors.accent}>ANTIQUE AI · ИСТОРИЧЕСКИЙ АРХИВ</Text><Button title="Пропустить" variant="ghost" onPress={finish} /></Row>{step === 0 ? <Animated.View entering={FadeIn.duration(500).reduceMotion(ReduceMotion.System)} style={{ gap: 26 }}><ImageBackground source={require('../../assets/samarkand-hero.png')} imageStyle={{ borderRadius: 28 }} style={{ minHeight: 285, justifyContent: 'flex-end', overflow: 'hidden', borderRadius: 28 }}><View style={{ backgroundColor: '#10283dcc', padding: 20, gap: 7 }}><Text variant="label" color="#9DE1E8">САМАРКАНД · ИСТОРИЧЕСКИЙ АРХИВ</Text><Text variant="title" color="#F6FCFD" style={{ fontSize: 32, lineHeight: 36 }}>У каждого предмета{ '\n' }есть история.</Text></View></ImageBackground><Text color={colors.muted}>Собирайте то, что имеет значение. Открывайте происхождение предметов и сохраняйте знания вместе с коллекцией.</Text><Row style={{ flexWrap: 'wrap' }}>{[{ icon: 'grid' as const, text: 'Личная коллекция' }, { icon: 'aperture' as const, text: 'Определение с AI' }, { icon: 'shopping-bag' as const, text: 'Покупка и продажа' }].map(x => <Card key={x.text} style={{ flexGrow: 1, minWidth: 130 }}><View style={{ width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.tint }}><Icon name={x.icon} color={colors.accent} size={21} /></View><Text variant="caption">{x.text}</Text></Card>)}</Row><Button title="Начать коллекцию" icon="arrow-right" onPress={() => setStep(1)} /></Animated.View> : <><Text variant="title">Что вы собираете?</Text><Text color={colors.muted}>Выберите интересы — мы подберём подходящие разделы. Их всегда можно изменить.</Text>{categories.isPending ? <LoadingSkeleton /> : categories.isError ? <ErrorState error={categories.error} retry={() => void categories.refetch()} /> : <Row style={{ flexWrap: 'wrap' }}>{categories.data.map(c => <Chip key={c.id} label={c.name} selected={ids.includes(c.id)} onPress={() => setIds(previous => previous.includes(c.id) ? previous.filter(id => id !== c.id) : [...previous, c.id])} />)}</Row>}<Button title="Продолжить" onPress={finish} /></>}<Text variant="caption" color={colors.muted} style={{ textAlign: 'center' }}>КОЛЛЕКЦИИ · ИСТОРИЯ · НОВЫЕ ОТКРЫТИЯ</Text></Screen>;
}
