import { useRef, useState } from 'react';
import { CameraView, useCameraPermissions } from 'expo-camera';

import { useMutation } from '@tanstack/react-query';
import { Linking, Switch, View } from 'react-native';
import { router, usePathname } from 'expo-router';
import { identificationApi } from '../shared/api/services';
import { newRequestKey } from '../shared/lib/hooks';
import { useMedia } from '../features/media/useMedia';
import { MediaPicker } from '../features/media/MediaPicker';
import { AuthGate } from '../widgets/AuthGate';
import { Button, Card, Field, Icon, InlineError, Row, Screen, ScreenHeader, Text } from '../shared/ui/core';
import { useTheme } from '../shared/ui/theme';
import { useI18n } from '../shared/lib/i18n';
export function ScanScreen() { return <AuthGate title="Определить предмет"><ScanContent /></AuthGate>; }
function ScanContent() {
  const { colors } = useTheme(); const { t } = useI18n(); const media = useMedia(); const [permission, requestPermission] = useCameraPermissions(); const camera = useRef<CameraView>(null); const focused = usePathname() === '/scan'; const [active, setActive] = useState(false); const [description, setDescription] = useState(''); const [allowWeb, setAllowWeb] = useState(false); const [taking, setTaking] = useState(false); const [captureError, setCaptureError] = useState<unknown>(null); const [key] = useState(newRequestKey);
  const analyze = useMutation({ mutationFn: async () => { const photos = await media.uploadAll(); return identificationApi.create({ mediaIds: photos.map(p => p.id), description, allowWeb }, key); }, onSuccess: result => router.push({ pathname: '/scan/result/[id]', params: { id: result.id } }) });
  async function takePhoto() { setTaking(true); try { const photo = await camera.current?.takePictureAsync({ quality: 0.85 }); if (photo) media.add([{ uri: photo.uri, name: `scan-${Date.now()}.jpg`, mimeType: 'image/jpeg' }]); setActive(false); } catch (error) { setCaptureError(error); } finally { setTaking(false); } }
  return <Screen><ScreenHeader title="Откройте историю" eyebrow="AI · АНАЛИЗ" /><Text color={colors.muted}>Монета, картина, слиток или семейная реликвия — начните с фотографии.</Text>{active && permission?.granted && focused ? <View style={{ height: 340, borderRadius: 24, overflow: 'hidden' }}><CameraView ref={camera} style={{ flex: 1 }} facing="back" /><View style={{ position: 'absolute', bottom: 18, left: 18, right: 18 }}><Button title={t('takePhoto')} icon="camera" loading={taking} onPress={() => void takePhoto()} /></View></View> : <Card style={{ minHeight: 230, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.hero }}><View style={{ width: 100, height: 100, borderWidth: 1, borderColor: '#8BD2DE', borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: '#1B5064' }}><Icon name="aperture" color="#B8EDF1" size={54} /></View><Text variant="heading" color={colors.inverse}>Новый взгляд на находку</Text><Text color="#D7EEF1" style={{ textAlign: 'center' }}>Чёткие детали помогают{ '\n' }найти более точное совпадение.</Text></Card>}<Row><View style={{ flex: 1, minWidth: 180 }}><Button title={active ? t('closeCamera') : t('camera')} icon="camera" disabled={media.count >= 8} onPress={() => { if (active) setActive(false); else if (permission?.granted) setActive(true); else void requestPermission().then(p => setActive(p.granted)).catch(setCaptureError); }} /></View>{permission && !permission.granted && !permission.canAskAgain ? <Button title="Настройки" variant="ghost" onPress={() => void Linking.openSettings()} /> : null}</Row><MediaPicker media={media} /><Card><Text variant="heading">Как получить точный результат</Text><Text color={colors.muted}>Для монет снимите лицевую и обратную стороны, затем гурт. Для других предметов — общий вид, клеймо и важные детали.</Text><Text variant="caption" color={colors.muted}>По снимку нельзя гарантировать подлинность, металл или пробу. Для подтверждения доступен осмотр специалиста.</Text></Card><Card style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><View style={{ flex: 1, paddingRight: 12 }}><Text variant="heading" style={{ fontSize: 16 }}>Поиск по внешним источникам</Text><Text variant="caption" color={colors.muted}>Добавит ссылки на найденные справочные материалы. AI всё равно не подтверждает подлинность.</Text></View><Switch value={allowWeb} onValueChange={setAllowWeb} trackColor={{ false: colors.border, true: colors.accent }} thumbColor={colors.inverse} /></Card><Field label="Что вы уже знаете? Необязательно" value={description} onChangeText={setDescription} multiline maxLength={3000} /><InlineError error={analyze.error || captureError} /><Button title={analyze.isPending ? 'Отправляем фотографии…' : t('identify')} loading={analyze.isPending} disabled={!media.count} onPress={() => analyze.mutate()} /></Screen>;
}
