import { Button, Card, Input, List, Select, Space, Tag, Typography, message } from "antd";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import axiosClient from "../api/axiosClient";

const statusLabels = { open: "Открыто", waiting_admin: "Ждём ответа", waiting_user: "Ждём пользователя", closed: "Закрыто" };

export default function Support() {
  const queryClient = useQueryClient(); const [selected, setSelected] = useState(null); const [text, setText] = useState("");
  const tickets = useQuery({ queryKey: ["support"], queryFn: async () => (await axiosClient.get("/admin/support")).data, refetchInterval: 10000 });
  const conversation = useQuery({ queryKey: ["support", selected?.id], queryFn: async () => (await axiosClient.get(`/admin/support/${selected.id}/messages`)).data, enabled: Boolean(selected?.id), refetchInterval: 10000 });
  useEffect(() => { if (conversation.data) setSelected(conversation.data.ticket); }, [conversation.data]);
  const reply = useMutation({ mutationFn: () => axiosClient.post(`/admin/support/${selected.id}/messages`, { message: text }), onSuccess: () => { setText(""); void queryClient.invalidateQueries({ queryKey: ["support"] }); message.success("Ответ отправлен"); } });
  const changeStatus = useMutation({ mutationFn: status => axiosClient.patch(`/admin/support/${selected.id}`, { status }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["support"] }); void queryClient.invalidateQueries({ queryKey: ["support", selected.id] }); } });
  return <Space align="start" style={{ width: "100%" }} size="large"><Card title="Обращения" style={{ width: 390 }} extra={<Button onClick={() => tickets.refetch()}>Обновить</Button>}><List loading={tickets.isLoading} dataSource={tickets.data?.items || []} renderItem={ticket => <List.Item onClick={() => setSelected(ticket)} style={{ cursor: "pointer", background: selected?.id === ticket.id ? "#f0f5ff" : undefined, padding: 12 }}><List.Item.Meta title={<Space>{ticket.subject}{ticket.unreadForAdmin > 0 ? <Tag color="red">{ticket.unreadForAdmin}</Tag> : null}</Space>} description={<>{ticket.owner?.name || "Коллекционер"} · {ticket.owner?.email}<br />Телефон: {ticket.phone}<br />{statusLabels[ticket.status]}<br />{ticket.lastMessage?.slice(0, 90)}</>} /></List.Item>} /></Card>{selected ? <Card title={<Space direction="vertical" align="start"><Typography.Text>{selected.subject}</Typography.Text><Typography.Text type="secondary">{selected.owner?.name} · {selected.owner?.email}</Typography.Text><Typography.Text type="secondary">Телефон: {selected.phone}</Typography.Text></Space>} extra={<Select value={selected.status} options={Object.entries(statusLabels).map(([value, label]) => ({ value, label }))} onChange={value => changeStatus.mutate(value)} />} style={{ flex: 1, minHeight: 560 }}><List dataSource={conversation.data?.items || []} loading={conversation.isLoading} renderItem={item => <List.Item><Card size="small" style={{ width: "100%", background: item.senderRole === "admin" ? "#f6ffed" : "#f5f5f5" }}><Typography.Text type="secondary">{item.senderRole === "admin" ? "Администратор" : "Пользователь"} · {new Date(item.createdAt).toLocaleString()}</Typography.Text><div>{item.text}</div></Card></List.Item>} /><Space.Compact style={{ width: "100%", marginTop: 16 }}><Input.TextArea value={text} onChange={event => setText(event.target.value)} placeholder="Ответ пользователю…" autoSize={{ minRows: 2, maxRows: 5 }} /><Button type="primary" loading={reply.isPending} disabled={!text.trim()} onClick={() => reply.mutate()}>Отправить</Button></Space.Compact></Card> : <Card style={{ flex: 1, minHeight: 560 }}><Typography.Text type="secondary">Выберите обращение слева</Typography.Text></Card>}</Space>;
}
