const catalogSeed = {
  slug: 'imperial-russia',
  title: 'Монеты Российской империи',
  subtitle: 'История России в металле',
  period: '1700–1917',
  country: 'Российская империя',
  rulers: [
    { slug: 'nicholas-ii', name: 'Николай II', years: '1894–1917' },
    { slug: 'alexander-iii', name: 'Александр III', years: '1881–1894' },
    { slug: 'alexander-ii', name: 'Александр II', years: '1855–1881' },
    { slug: 'nicholas-i', name: 'Николай I', years: '1825–1855' },
    { slug: 'alexander-i', name: 'Александр I', years: '1801–1825' },
    { slug: 'paul-i', name: 'Павел I', years: '1796–1801' },
  ],
  denominations: [
    { slug: 'quarter-kopeck', label: '1/4 копейки', metal: 'медь' },
    { slug: 'half-kopeck', label: '1/2 копейки', metal: 'медь' },
    { slug: '1-kopeck', label: '1 копейка', metal: 'медь' },
    { slug: '2-kopecks', label: '2 копейки', metal: 'медь' },
    { slug: '3-kopecks', label: '3 копейки', metal: 'медь' },
    { slug: '5-kopecks', label: '5 копеек', metal: 'медь' },
    { slug: '10-kopecks', label: '10 копеек', metal: 'серебро' },
    { slug: '15-kopecks', label: '15 копеек', metal: 'серебро' },
    { slug: '20-kopecks', label: '20 копеек', metal: 'серебро' },
    { slug: '25-kopecks', label: '25 копеек', metal: 'серебро' },
    { slug: 'half-ruble', label: '50 копеек', metal: 'серебро' },
    { slug: 'ruble', label: '1 рубль', metal: 'серебро' },
  ],
  coins: [
    { slug: 'nicholas-ii-1-kopeck-1894-spb', title: '1 копейка 1894', ruler: 'nicholas-ii', denomination: '1-kopeck', year: '1894', mint: 'СПБ', metal: 'медь', weight: '3.28 г', diameter: '21.7 мм', mintage: '1 800 000', description: 'Медная монета периода правления Николая II.', price: { amount: '12', currency: 'USD' } },
    { slug: 'nicholas-ii-1-kopeck-1895-spb', title: '1 копейка 1895', ruler: 'nicholas-ii', denomination: '1-kopeck', year: '1895', mint: 'СПБ', metal: 'медь', weight: '3.28 г', diameter: '21.7 мм', mintage: '—', description: 'Распространённый тип медной монеты.', price: { amount: '90', currency: 'USD' } },
    { slug: 'nicholas-ii-5-kopecks-1896-spb', title: '5 копеек 1896', ruler: 'nicholas-ii', denomination: '5-kopecks', year: '1896', mint: 'СПБ', metal: 'медь', weight: '16.38 г', diameter: '32 мм', mintage: '—', description: 'Крупная медная монета Николая II.', price: { amount: '52', currency: 'USD' } },
    { slug: 'alexander-iii-1-ruble-1893-spb', title: '1 рубль 1893', ruler: 'alexander-iii', denomination: 'ruble', year: '1893', mint: 'СПБ', metal: 'серебро', weight: '20 г', diameter: '33.65 мм', mintage: '—', description: 'Серебряный рубль последнего года правления Александра III.', price: { amount: '180', currency: 'USD' } },
    { slug: 'alexander-ii-20-kopecks-1876-spb', title: '20 копеек 1876', ruler: 'alexander-ii', denomination: '20-kopecks', year: '1876', mint: 'СПБ', metal: 'серебро', weight: '4.27 г', diameter: '22 мм', mintage: '—', description: 'Серебряные 20 копеек эпохи Александра II.', price: { amount: '35', currency: 'USD' } },
    { slug: 'nicholas-i-5-kopecks-1839-spb', title: '5 копеек 1839', ruler: 'nicholas-i', denomination: '5-kopecks', year: '1839', mint: 'СПБ', metal: 'медь', weight: '22.7 г', diameter: '36 мм', mintage: '—', description: 'Медная монета Николая I с гербовым орлом.', price: { amount: '45', currency: 'USD' } },
  ],
};

const muslimCatalogSeed = {
  slug: 'muslim-world',
  title: 'Мусульманские монеты',
  subtitle: 'Династии, золото и серебро от Омейядов до Центральной Азии',
  period: '661–XX век',
  country: 'Мусульманский мир',
  rulers: [
    { slug: 'umayyads', name: 'Омейяды', years: '661–750' },
    { slug: 'abbasids', name: 'Аббасиды', years: '750–1258' },
    { slug: 'samanids', name: 'Саманиды', years: '819–999' },
    { slug: 'qara-khanids', name: 'Караханиды', years: '840–1212' },
    { slug: 'khwarazmshahs', name: 'Хорезмшахи', years: '1077–1231' },
    { slug: 'timurids', name: 'Тимуриды', years: '1370–1507' },
    { slug: 'shaybanids', name: 'Шейбаниды', years: '1500–1599' },
    { slug: 'bukhara-emirate', name: 'Бухарский эмират', years: '1785–1920' },
    { slug: 'khiva-khanate', name: 'Хивинское ханство', years: '1511–1920' },
    { slug: 'kokand-khanate', name: 'Кокандское ханство', years: '1709–1876' },
    { slug: 'ottomans', name: 'Османская империя', years: '1299–1922' },
    { slug: 'safavids', name: 'Сефевиды', years: '1501–1736' },
    { slug: 'qajars', name: 'Каджары', years: '1789–1925' },
  ],
  denominations: [],
  coins: [],
};

module.exports = { catalogSeed, muslimCatalogSeed };
