const express = require('express');
const axios = require('axios');
const multer = require('multer');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const mobileAuth = require('./auth.middleware');
const auth = require('./auth.controller');
const { item, media, request, user, legacyRequest } = require('./format');
const Category = require('../models/Category');
const CollectionItem = require('../models/CollectionItem');
const MarketplaceListing = require('../models/MarketplaceListing');
const MarketplaceMessage = require('../models/MarketplaceMessage');
const SavedSearch = require('../models/SavedSearch');
const CollectorRequest = require('../models/CollectorRequest');
const MediaAsset = require('../models/MediaAsset');
const Notification = require('../models/Notification');
const IdentificationJob = require('../models/IdentificationJob');
const AssistantMessage = require('../models/AssistantMessage');
const TelegramLinkCode = require('../models/TelegramLinkCode');
const Post = require('../models/Post');
const Estimate = require('../models/Estimate');
const Order = require('../models/Order');
const claude = require('./claude');
const CoinCatalog = require('../models/CoinCatalog');
const { catalogSeed, muslimCatalogSeed } = require('./catalogSeed');
const support = require('../api/controllers/support.controller');

const router = express.Router();
fs.mkdirSync(path.join(process.cwd(), 'uploads/mobile'), { recursive: true });
const upload = multer({ dest: path.join(process.cwd(), 'uploads/mobile'), limits: { fileSize: 8 * 1024 * 1024, files: 5 }, fileFilter: (_req, file, callback) => callback(null, /^image\/(jpeg|png|webp|gif)$/.test(file.mimetype)) });
const page = (items, total) => ({ items, nextCursor: null, total });
const clean = value => value === undefined || value === null ? undefined : String(value).slice(0, 500);
const filters = query => Object.fromEntries(Object.entries(query).filter(([key, value]) => ['search', 'categoryId', 'country', 'material', 'metal', 'fineness', 'form', 'manufacturer', 'favorite'].includes(key) && value !== undefined));
const categorySeed = [
  ['Монеты', 'coins', null], ['Иконы', 'icons', null], ['Часы', 'watches', null], ['Ювелирные изделия', 'jewelry', 'gold'], ['Золотые монеты', 'gold-coins', 'gold'], ['Серебряные монеты', 'silver-coins', 'silver'], ['Слитки', 'bars', 'gold'],
];
let quoteCache = { expiresAt: 0, values: null };
async function ensureCategories() { if (await Category.countDocuments()) return; await Category.insertMany(categorySeed.map(([name, slug, metal]) => ({ name, slug, metal, attributes: metal ? [{ key: 'fineness', label: 'Проба', type: 'text' }, { key: 'weight', label: 'Вес', type: 'number', unit: 'г' }, { key: 'form', label: 'Форма', type: 'text' }] : [] })), { ordered: false }).catch(() => {}); }
async function ensureCoinCatalog() { if (!await CoinCatalog.exists({ slug: catalogSeed.slug })) await CoinCatalog.create(catalogSeed); if (!await CoinCatalog.exists({ slug: muslimCatalogSeed.slug })) await CoinCatalog.create(muslimCatalogSeed); }
const absoluteMediaUrl = (req, value) => value && value.startsWith('/') ? `${req.protocol}://${req.get('host')}${value}` : value;
const metalLabel = value => ({ gold: 'Золото', silver: 'Серебро', copper: 'Медь', bronze: 'Бронза' }[String(value || '').toLowerCase()] || value);
const sellerSummary = seller => { const value = seller && typeof seller === 'object' ? seller : null; const verified = Boolean(value?.phoneVerified && value?.identityVerified); return { id: String(value?._id || seller), name: value?.name || 'Продавец', verified }; };
const coinResponse = (req, coin) => { const result = coin.toObject ? coin.toObject() : { ...coin }; result.metal = metalLabel(result.metal); result.imageUrl = absoluteMediaUrl(req, result.imageUrl); result.imageUrls = (result.imageUrls || []).map(value => absoluteMediaUrl(req, value)); return result; };
function queryForItems(query) { const result = {}; for (const key of ['categoryId', 'country', 'material']) if (query[key]) result[key] = new RegExp(String(query[key]).slice(0, 80), 'i'); if (query.search) result.$or = ['title', 'description', 'material', 'country'].map(key => ({ [key]: new RegExp(String(query.search).slice(0, 80), 'i') })); if (query.favorite === 'true') result.favorite = true; if (query.metal) result['attributes.metal'] = query.metal; return result; }

router.post('/auth/register', auth.register); router.post('/auth/login', auth.login); router.post('/auth/refresh', auth.refresh);
router.post('/auth/forgot-password', (_req, res) => res.json({ success: true }));
router.post('/auth/reset-password', (_req, res) => res.json({ success: true }));
router.get('/auth/me', mobileAuth, auth.me); router.post('/auth/logout', mobileAuth, auth.logout);
router.get('/categories', async (_req, res, next) => { try { await ensureCategories(); const values = await Category.find().sort({ name: 1 }); res.json(values.map(value => ({ id: String(value._id), parentId: value.parentId, name: value.name, slug: value.slug, attributes: value.attributes, ...(value.metal ? { metal: value.metal } : {}) }))); } catch (error) { next(error); } });
router.get('/coin-catalogs', async (req, res, next) => { try { await ensureCoinCatalog(); const values = await CoinCatalog.find().select('slug title subtitle period country coverUrl rulers coins'); res.json(values.map(value => ({ id: String(value._id), slug: value.slug, title: value.title, subtitle: value.subtitle, period: value.period, country: value.country, coverUrl: absoluteMediaUrl(req, value.coverUrl || value.coins.find(coin => coin.imageUrl)?.imageUrl), rulerCount: value.rulers.length, coinCount: value.coins.length }))); } catch (error) { next(error); } });
router.get('/coin-catalogs/:slug', async (req, res, next) => { try { await ensureCoinCatalog(); const value = await CoinCatalog.findOne({ slug: req.params.slug }); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Каталог не найден' }); res.json({ id: String(value._id), slug: value.slug, title: value.title, subtitle: value.subtitle, period: value.period, country: value.country, coverUrl: absoluteMediaUrl(req, value.coverUrl || value.coins.find(coin => coin.imageUrl)?.imageUrl), rulerCount: value.rulers.length, coinCount: value.coins.length }); } catch (error) { next(error); } });
router.get('/coin-catalogs/:slug/rulers', async (req, res, next) => { try { await ensureCoinCatalog(); const value = await CoinCatalog.findOne({ slug: req.params.slug }).select('rulers'); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Каталог не найден' }); res.json(value.rulers.map(ruler => ({ ...(ruler.toObject ? ruler.toObject() : ruler), portraitUrl: absoluteMediaUrl(req, ruler.portraitUrl) }))); } catch (error) { next(error); } });
router.get('/coin-catalogs/:slug/denominations', async (req, res, next) => { try { await ensureCoinCatalog(); const value = await CoinCatalog.findOne({ slug: req.params.slug }).select('denominations coins'); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Каталог не найден' }); const coins = value.coins.filter(coin => !req.query.ruler || coin.ruler === req.query.ruler); const used = new Set(coins.map(coin => coin.denomination)); res.json(value.denominations.filter(denomination => used.has(denomination.slug)).map(denomination => { const preview = coins.find(coin => coin.denomination === denomination.slug); const imageUrls = (preview?.imageUrls?.length ? preview.imageUrls : preview?.imageUrl ? [preview.imageUrl] : []).slice(0, 2).map(image => absoluteMediaUrl(req, image)); return { ...(denomination.toObject ? denomination.toObject() : denomination), imageUrls }; })); } catch (error) { next(error); } });
router.get('/coin-catalogs/:slug/coins', async (req, res, next) => { try { await ensureCoinCatalog(); const value = await CoinCatalog.findOne({ slug: req.params.slug }).select('coins'); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Каталог не найден' }); const search = String(req.query.search || '').toLowerCase(); const items = value.coins.filter(coin => (!req.query.ruler || coin.ruler === req.query.ruler) && (!req.query.denomination || coin.denomination === req.query.denomination) && (!search || `${coin.title} ${coin.year} ${coin.mint}`.toLowerCase().includes(search))); res.json(items.map(coin => coinResponse(req, coin))); } catch (error) { next(error); } });
router.get('/coin-catalogs/:slug/coins/:coinSlug', async (req, res, next) => { try { await ensureCoinCatalog(); const value = await CoinCatalog.findOne({ slug: req.params.slug }).select('coins'); const coin = value?.coins.find(item => item.slug === req.params.coinSlug); if (!coin) return res.status(404).json({ code: 'NOT_FOUND', message: 'Монета не найдена' }); res.json(coinResponse(req, coin)); } catch (error) { next(error); } });
router.get('/catalog', async (req, res, next) => { try { const query = queryForItems(req.query); const values = await CollectionItem.find({ ...query, ownerId: { $exists: false } }).sort({ createdAt: -1 }).limit(20); const listings = await MarketplaceListing.find({ status: 'approved' }).sort({ createdAt: -1 }).limit(20); const result = values.map(value => item(value)).concat(listings.map(value => item(value.item))); res.json(page(result.slice(0, 20), result.length)); } catch (error) { next(error); } });

router.get('/marketplace', async (req, res, next) => { try { const query = { status: 'approved' }; if (req.query.metal) query['item.attributes.metal'] = req.query.metal; if (req.query.search) query.$or = ['item.title', 'item.description', 'item.material'].map(key => ({ [key]: new RegExp(String(req.query.search).slice(0, 80), 'i') })); const values = await MarketplaceListing.find(query).populate('sellerId', 'name email phoneVerified identityVerified').sort({ createdAt: -1 }).limit(50); const telegramPosts = await Post.find({ type: 'sell', status: 'approved' }).sort({ createdAt: -1 }).limit(50); const listings = values.map(value => item(value.item, { price: value.price, priceType: value.priceType, seller: sellerSummary(value.sellerId), location: value.location, status: value.status })); const posts = telegramPosts.map(post => item({ id: String(post._id), collectionCode: post.uniqueCode, title: post.title || 'Предмет из Telegram', categoryId: 'telegram', categoryName: 'Антиквариат', photos: [], description: post.description, condition: post.condition, material: post.type, attributes: {}, favorite: false, sources: [], createdAt: post.createdAt }, { price: { amount: post.price || '0', currency: 'UZS' }, priceType: 'negotiable', seller: { id: String(post.userId), name: post.username || 'Продавец Telegram', verified: false }, location: post.city || '', status: post.status })); res.json(page([...listings, ...posts].slice(0, 50), listings.length + posts.length)); } catch (error) { next(error); } });
router.get('/marketplace/:id', async (req, res, next) => { try { const value = await MarketplaceListing.findOne({ _id: req.params.id, status: { $ne: 'rejected' } }).populate('sellerId', 'name email phoneVerified identityVerified'); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Объявление не найдено' }); res.json(item(value.item, { price: value.price, priceType: value.priceType, seller: sellerSummary(value.sellerId), location: value.location, status: value.status })); } catch (error) { next(error); } });
router.get('/metals/quotes', async (_req, res) => { try { if (quoteCache.values && quoteCache.expiresAt > Date.now()) return res.json(quoteCache.values); const baseUrl = String(process.env.METALS_API_BASE_URL || 'https://api.gold-api.com/price').replace(/\/$/, ''); const [goldResponse, silverResponse] = await Promise.all([axios.get(`${baseUrl}/XAU`, { timeout: 5000 }), axios.get(`${baseUrl}/XAG`, { timeout: 5000 })]); const ounce = { gold: Number(goldResponse.data?.price), silver: Number(silverResponse.data?.price) }; if (!Number.isFinite(ounce.gold) || !Number.isFinite(ounce.silver)) throw new Error('Invalid metal quote payload'); const asOf = new Date().toISOString(); const source = { title: 'Gold API spot reference', url: 'https://gold-api.com/', domain: 'gold-api.com' }; const values = ['gold', 'silver'].map(metal => ({ metal, perGram: { amount: (ounce[metal] / 31.1034768).toFixed(2), currency: 'USD' }, perTroyOunce: { amount: ounce[metal].toFixed(2), currency: 'USD' }, changePercent: 0, asOf, source })); quoteCache = { values, expiresAt: Date.now() + 5 * 60 * 1000 }; res.json(values); } catch (error) { res.status(503).json({ code: 'METAL_QUOTES_UNAVAILABLE', message: 'Котировки металлов временно недоступны' }); } });

router.use(mobileAuth);
router.get('/profile', (req, res) => res.json(user(req.collector))); router.patch('/profile', auth.profile);
router.post('/profile/link-telegram', async (req, res, next) => { try { const code = String(req.body?.code || '').trim().toUpperCase(); const link = await TelegramLinkCode.findOne({ code, usedAt: { $exists: false }, expiresAt: { $gt: new Date() } }); if (!link) return res.status(400).json({ code: 'INVALID_LINK_CODE', message: 'Код недействителен или истёк' }); req.collector.telegramId = link.telegramId; req.collector.telegramUsername = link.username || null; await req.collector.save(); link.usedAt = new Date(); await link.save(); res.json(user(req.collector)); } catch (error) { next(error); } });
router.get('/collection', async (req, res, next) => { try { const query = queryForItems(req.query); const values = await CollectionItem.find({ ownerId: req.collector._id, ...query }).sort({ createdAt: -1 }).limit(50); res.json(page(values.map(value => item(value)), values.length)); } catch (error) { next(error); } });
router.post('/collection', async (req, res, next) => { try { const body = req.body || {}; if (!String(body.title || '').trim() || !String(body.categoryId || '').trim()) return res.status(400).json({ code: 'INVALID_ITEM', message: 'Название и категория обязательны' }); const record = await CollectionItem.create({ ...body, ownerId: req.collector._id, title: clean(body.title), categoryName: clean(body.categoryName) || 'Без категории', attributes: body.attributes || {} }); res.status(201).json(item(record)); } catch (error) { next(error); } });
router.get('/collection/statistics', async (req, res, next) => { try { const values = await CollectionItem.find({ ownerId: req.collector._id }); const countries = new Set(values.map(value => value.country).filter(Boolean)); let gold = 0; let silver = 0; for (const value of values) { const grams = Number(value.attributes?.get?.('weight') || value.attributes?.weight || 0); const metal = String(value.attributes?.get?.('metal') || value.attributes?.metal || '').toLowerCase(); if (metal === 'gold') gold += grams; if (metal === 'silver') silver += grams; } res.json({ total: values.length, categories: new Set(values.map(value => value.categoryId)).size, countries: countries.size, activeRequests: await CollectorRequest.countDocuments({ ownerId: req.collector._id, status: { $nin: ['completed', 'rejected'] } }), goldWeightGrams: gold ? gold.toFixed(2) : undefined, silverWeightGrams: silver ? silver.toFixed(2) : undefined }); } catch (error) { next(error); } });
router.get('/collection/:id', async (req, res, next) => { try { const value = await CollectionItem.findOne({ _id: req.params.id, ownerId: req.collector._id }); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Предмет не найден' }); res.json(item(value)); } catch (error) { next(error); } });
router.patch('/collection/:id', async (req, res, next) => { try { const value = await CollectionItem.findOneAndUpdate({ _id: req.params.id, ownerId: req.collector._id }, { $set: req.body || {} }, { new: true }); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Предмет не найден' }); res.json(item(value)); } catch (error) { next(error); } });
router.delete('/collection/:id', async (req, res, next) => { try { const result = await CollectionItem.deleteOne({ _id: req.params.id, ownerId: req.collector._id }); if (!result.deletedCount) return res.status(404).json({ code: 'NOT_FOUND', message: 'Предмет не найден' }); res.json({ success: true }); } catch (error) { next(error); } });

router.post('/marketplace', async (req, res, next) => { try { const body = req.body || {}; const record = await MarketplaceListing.create({ sellerId: req.collector._id, item: { ...body, id: body.id || crypto.randomUUID(), categoryName: body.categoryName || 'Без категории', createdAt: new Date().toISOString() }, price: body.price, priceType: body.priceType || 'fixed', location: body.location, status: 'pending' }); res.status(201).json(item(record.item, { price: record.price, priceType: record.priceType, seller: sellerSummary(req.collector), location: record.location, status: record.status })); } catch (error) { next(error); } });
router.post('/marketplace/:id/purchase-requests', async (req, res, next) => { try { const listing = await MarketplaceListing.findById(req.params.id); if (!listing) return res.status(404).json({ code: 'NOT_FOUND', message: 'Объявление не найдено' }); const record = await CollectorRequest.create({ ownerId: req.collector._id, kind: 'purchase', title: listing.item.title, listingId: String(listing._id), history: [{ status: 'pending', at: new Date() }] }); res.status(201).json(request(record)); } catch (error) { next(error); } });
router.get('/marketplace/:id/messages', async (req, res, next) => { try { const listing = await MarketplaceListing.findById(req.params.id); if (!listing) return res.status(404).json({ code: 'NOT_FOUND', message: 'Объявление не найдено' }); const isSeller = String(listing.sellerId) === String(req.collector._id); const isParticipant = Boolean(await MarketplaceMessage.exists({ listingId: listing._id, $or: [{ senderId: req.collector._id }, { recipientId: req.collector._id }] })); if (!isSeller && !isParticipant) return res.status(403).json({ code: 'FORBIDDEN', message: 'Нет доступа к переписке' }); const values = await MarketplaceMessage.find({ listingId: listing._id, $or: [{ senderId: req.collector._id }, { recipientId: req.collector._id }] }).sort({ createdAt: 1 }); await MarketplaceMessage.updateMany({ listingId: listing._id, recipientId: req.collector._id }, { $set: { read: true } }); res.json(values.map(value => ({ id: String(value._id), listingId: String(value.listingId), senderId: String(value.senderId), recipientId: String(value.recipientId), text: value.text, read: value.read, createdAt: value.createdAt.toISOString() }))); } catch (error) { next(error); } });
router.post('/marketplace/:id/messages', async (req, res, next) => { try { const listing = await MarketplaceListing.findOne({ _id: req.params.id, status: 'approved' }); const text = clean(req.body?.text); if (!listing) return res.status(404).json({ code: 'NOT_FOUND', message: 'Объявление не найдено' }); if (!text) return res.status(400).json({ code: 'INVALID_MESSAGE', message: 'Введите сообщение' }); const isSeller = String(listing.sellerId) === String(req.collector._id); let recipientId = listing.sellerId; if (isSeller) { const previous = await MarketplaceMessage.findOne({ listingId: listing._id, $or: [{ senderId: req.collector._id }, { recipientId: req.collector._id }] }).sort({ createdAt: -1 }); if (!previous) return res.status(400).json({ code: 'NO_CONVERSATION', message: 'Сначала дождитесь сообщения покупателя' }); recipientId = String(previous.senderId) === String(req.collector._id) ? previous.recipientId : previous.senderId; } else { const existing = await MarketplaceMessage.exists({ listingId: listing._id, senderId: req.collector._id, recipientId: listing.sellerId }); if (!existing && String(listing.sellerId) === String(req.collector._id)) return res.status(400).json({ code: 'INVALID_RECIPIENT', message: 'Нельзя написать самому себе' }); } const message = await MarketplaceMessage.create({ listingId: listing._id, senderId: req.collector._id, recipientId, text, read: false }); await Notification.create({ ownerId: recipientId, title: 'Новое сообщение по объявлению', body: text.slice(0, 180), target: { kind: 'listing', id: String(listing._id) } }); res.status(201).json({ id: String(message._id), listingId: String(message.listingId), senderId: String(message.senderId), recipientId: String(message.recipientId), text: message.text, read: message.read, createdAt: message.createdAt.toISOString() }); } catch (error) { next(error); } });
router.post('/metals/valuation', (req, res) => res.json({ value: req.body?.value || { amount: '0', currency: 'USD' }, asOf: new Date().toISOString(), source: { title: 'Backend valuation', url: 'https://www.lbma.org.uk/prices-and-data/precious-metal-prices', domain: 'lbma.org.uk' } }));

router.post('/media', upload.array('file', 5), async (req, res, next) => { try { const files = req.files || []; fs.mkdirSync(path.join(process.cwd(), 'uploads/mobile'), { recursive: true }); const value = files[0]; if (!value) return res.status(400).json({ code: 'NO_FILE', message: 'Добавьте изображение' }); const asset = await MediaAsset.create({ ownerId: req.collector._id, url: `/uploads/mobile/${value.filename}`, kind: 'image', filename: value.originalname, mimeType: value.mimetype, size: value.size }); res.status(201).json(media(asset)); } catch (error) { next(error); } });
router.get('/requests', async (req, res, next) => { try { const query = { ownerId: req.collector._id }; if (req.query.kind && req.query.kind !== 'all') query.kind = req.query.kind; const values = await CollectorRequest.find(query).sort({ createdAt: -1 }).limit(50); const result = values.map(request); const telegramId = req.collector.telegramId; if (telegramId) { const [posts, estimates, orders] = await Promise.all([Post.find({ userId: telegramId, type: 'buy' }).sort({ createdAt: -1 }).limit(50), Estimate.find({ userId: telegramId }).sort({ createdAt: -1 }).limit(50), Order.find({ userId: Number(telegramId) }).sort({ createdAt: -1 }).limit(50)]); result.push(...posts.map(value => legacyRequest(value, 'buy', value.title, value.description)), ...estimates.map(value => legacyRequest(value, 'inspection', 'Оценка предмета', value.description)), ...orders.map(value => legacyRequest(value, 'purchase', value.itemName, value.description))); } result.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()); res.json(page(result.slice(0, 50), result.length)); } catch (error) { next(error); } });
router.post('/requests', async (req, res, next) => { try { const body = req.body || {}; if (body.kind === 'inspection' && (!Array.isArray(body.mediaIds) || !body.mediaIds.length)) return res.status(400).json({ code: 'PHOTO_REQUIRED', message: 'Для профессиональной оценки добавьте хотя бы одно фото.' }); const record = await CollectorRequest.create({ ...body, ownerId: req.collector._id, history: [{ status: 'pending', at: new Date() }] }); res.status(201).json(request(record)); } catch (error) { next(error); } });
router.get('/requests/:id', async (req, res, next) => { try { const value = await CollectorRequest.findOne({ _id: req.params.id, ownerId: req.collector._id }); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Заявка не найдена' }); res.json(request(value)); } catch (error) { next(error); } });

router.post('/identifications', async (req, res, next) => { try { const mediaIds = Array.isArray(req.body?.mediaIds) ? req.body.mediaIds.map(String).filter(Boolean).slice(0, 8) : []; if (!mediaIds.length) return res.status(400).json({ code: 'PHOTO_REQUIRED', message: 'Добавьте хотя бы одну фотографию предмета' }); const ownedMedia = await MediaAsset.countDocuments({ ownerId: req.collector._id, _id: { $in: mediaIds } }); if (ownedMedia !== mediaIds.length) return res.status(400).json({ code: 'INVALID_PHOTOS', message: 'Некоторые фотографии недоступны для анализа' }); const record = await IdentificationJob.create({ ownerId: req.collector._id, mediaIds, description: clean(req.body?.description), allowWeb: Boolean(req.body?.allowWeb), status: 'queued', canSearchWeb: Boolean(req.body?.allowWeb) }); setImmediate(async () => { try { await IdentificationJob.updateOne({ _id: record._id }, { $set: { status: 'reading_image' } }); const result = await claude.identify(req.collector._id, record.mediaIds, record.description); await IdentificationJob.updateOne({ _id: record._id }, { $set: { status: 'completed', candidates: result.candidates, sources: result.sources } }); } catch (error) { await IdentificationJob.updateOne({ _id: record._id }, { $set: { status: 'failed', error: error.message === 'AI provider is not configured on this backend' ? error.message : 'AI analysis failed' } }); } }); res.status(202).json({ id: String(record._id), status: record.status, candidates: [], sources: [], canSearchWeb: record.canSearchWeb }); } catch (error) { next(error); } });
router.get('/identifications/:id', async (req, res, next) => { try { const value = await IdentificationJob.findOne({ _id: req.params.id, ownerId: req.collector._id }); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Задача не найдена' }); res.json({ id: String(value._id), status: value.status, candidates: value.candidates, sources: value.sources, error: value.error, canSearchWeb: value.canSearchWeb }); } catch (error) { next(error); } });
router.post('/identifications/:id/feedback', (_req, res) => res.json({ success: true })); router.post('/identifications/:id/web-search', async (req, res, next) => { try { const value = await IdentificationJob.findOne({ _id: req.params.id, ownerId: req.collector._id }); if (!value) return res.status(404).json({ code: 'NOT_FOUND', message: 'Задача не найдена' }); if (!value.canSearchWeb) return res.status(403).json({ code: 'WEB_SEARCH_NOT_ALLOWED', message: 'Разрешите поиск по внешним источникам перед анализом' }); const queries = (value.candidates || []).map(candidate => candidate.item?.title).filter(Boolean); const sources = await claude.webSearch(queries.length ? queries : [value.description]); value.sources = sources; value.candidates = (value.candidates || []).map(candidate => ({ ...candidate, origin: 'web' })); await value.save(); res.json({ id: String(value._id), status: value.status, candidates: value.candidates, sources: value.sources, canSearchWeb: false }); } catch (error) { next(error); } });
router.get('/notifications', async (req, res, next) => { try { const values = await Notification.find({ ownerId: req.collector._id }).sort({ createdAt: -1 }).limit(50); res.json(page(values.map(value => ({ id: String(value._id), title: value.title, body: value.body, read: value.read, createdAt: value.createdAt.toISOString(), ...(value.target?.kind ? { target: value.target } : {}) })), values.length)); } catch (error) { next(error); } });
router.patch('/notifications/:id', async (req, res, next) => { try { await Notification.updateOne({ _id: req.params.id, ownerId: req.collector._id }, { $set: { read: true } }); res.json({ success: true }); } catch (error) { next(error); } }); router.post('/notifications/devices', (_req, res) => res.json({ success: true })); router.delete('/notifications/devices', (_req, res) => res.json({ success: true }));
router.get('/saved-searches', async (req, res, next) => { try { const values = await SavedSearch.find({ ownerId: req.collector._id }).sort({ createdAt: -1 }); res.json(values.map(value => ({ id: String(value._id), name: value.name, filters: Object.fromEntries(value.filters || []), alertsEnabled: value.alertsEnabled, createdAt: value.createdAt.toISOString() }))); } catch (error) { next(error); } });
router.post('/saved-searches', async (req, res, next) => { try { const name = clean(req.body?.name).slice(0, 120); const filtersValue = req.body?.filters && typeof req.body.filters === 'object' ? req.body.filters : {}; if (!name) return res.status(400).json({ code: 'INVALID_SAVED_SEARCH', message: 'Укажите название поиска' }); const value = await SavedSearch.create({ ownerId: req.collector._id, name, filters: filtersValue, alertsEnabled: req.body?.alertsEnabled !== false }); res.status(201).json({ id: String(value._id), name: value.name, filters: Object.fromEntries(value.filters || []), alertsEnabled: value.alertsEnabled, createdAt: value.createdAt.toISOString() }); } catch (error) { next(error); } });
router.delete('/saved-searches/:id', async (req, res, next) => { try { const result = await SavedSearch.deleteOne({ _id: req.params.id, ownerId: req.collector._id }); if (!result.deletedCount) return res.status(404).json({ code: 'NOT_FOUND', message: 'Поиск не найден' }); res.json({ success: true }); } catch (error) { next(error); } });
router.get('/support', support.list);
router.post('/support', support.create);
router.get('/support/:id/messages', support.messages);
router.post('/support/:id/messages', support.reply);
router.get('/assistant/messages', async (req, res, next) => { try { const values = await AssistantMessage.find({ ownerId: req.collector._id }).sort({ createdAt: -1 }).limit(30); res.json(page(values.reverse().map(value => ({ id: String(value._id), role: value.role, text: value.text, itemIds: value.itemIds || [], sources: value.sources || [], createdAt: value.createdAt.toISOString() })), values.length)); } catch (error) { next(error); } });
router.post('/assistant/messages', async (req, res, next) => { try { const text = clean(req.body?.text); if (!text) return res.status(400).json({ code: 'INVALID_MESSAGE', message: 'Введите вопрос' }); await AssistantMessage.create({ ownerId: req.collector._id, role: 'user', text, itemIds: req.body?.itemId ? [String(req.body.itemId)] : [] }); const answer = await claude.answerCollection(req.collector._id, text); const saved = await AssistantMessage.create({ ownerId: req.collector._id, role: 'assistant', text: String(answer.text || 'Не удалось подготовить ответ.'), itemIds: Array.isArray(answer.itemIds) ? answer.itemIds.map(String).slice(0, 12) : [], sources: [] }); res.status(201).json({ id: String(saved._id), role: saved.role, text: saved.text, itemIds: saved.itemIds, sources: saved.sources, createdAt: saved.createdAt.toISOString() }); } catch (error) { next(error); } });

module.exports = router;
