import { Feather } from '@expo/vector-icons';
import { router, usePathname, type Href } from 'expo-router';
import { type ComponentProps, type PropsWithChildren } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Modal as NativeModal, Platform, Pressable, ScrollView, StyleSheet, Text as NativeText, TextInput as NativeInput, View, type ColorValue, type StyleProp, type TextStyle, type ViewStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTheme } from './theme';
import { errorMessage } from '../api/transport';
import { translateStatic, useI18n } from '../lib/i18n';

export type IconName = ComponentProps<typeof Feather>['name'];
export function Icon({ name, size = 22, color }: { name: IconName; size?: number; color?: ColorValue }) { const { colors } = useTheme(); return <Feather name={name} size={size} color={color ?? colors.text} strokeWidth={2.4} />; }
export function Text({ children, variant = 'body', color, style, ...props }: PropsWithChildren<{ variant?: 'body' | 'title' | 'heading' | 'label' | 'caption'; color?: string; style?: StyleProp<TextStyle> }> & ComponentProps<typeof NativeText>) {
  const t = useTheme();
  const { language } = useI18n();
  const renderedChildren = typeof children === 'string' ? translateStatic(language, children) : children;
  return <NativeText {...props} style={[{ color: color ?? t.colors.text, fontFamily: variant === 'title' ? t.font.display : variant === 'heading' || variant === 'label' ? t.font.bold : t.font.body, fontSize: variant === 'title' ? 32 : variant === 'heading' ? 18 : variant === 'caption' ? 12 : variant === 'label' ? 12 : 15, lineHeight: variant === 'title' ? 36 : variant === 'heading' ? 24 : variant === 'caption' ? 17 : 22, ...(variant === 'label' ? { letterSpacing: 1.05, textTransform: 'uppercase' as const } : {}) }, style]}>{renderedChildren}</NativeText>;
}
export function Screen({ children, scroll = true, style }: PropsWithChildren<{ scroll?: boolean; style?: StyleProp<ViewStyle> }>) {
  const { colors } = useTheme();
  return <SafeAreaView edges={['top', 'left', 'right']} style={{ flex: 1, backgroundColor: colors.background }}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>{scroll ? <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[styles.content, style]}>{children}</ScrollView> : <View style={[styles.content, { flex: 1, paddingBottom: 0 }, style]}>{children}</View>}</KeyboardAvoidingView></SafeAreaView>;
}
export function Row({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { return <View style={[styles.row, style]}>{children}</View>; }
export function Card({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { const { colors, radius } = useTheme(); return <View style={[{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: 16, gap: 10, minWidth: 0 }, style]}>{children}</View>; }
export function Button({ title, onPress, variant = 'primary', icon, loading, disabled, style }: { title: string; onPress: () => void; variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger'; icon?: IconName; loading?: boolean; disabled?: boolean; style?: StyleProp<ViewStyle> }) {
  const { colors } = useTheme();
  const color = variant === 'primary' ? colors.inverse : variant === 'danger' ? colors.danger : colors.text;
  const isOutline = variant === 'outline' || variant === 'danger';
  return <Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityState={{ disabled: disabled || loading, busy: loading }} disabled={disabled || loading} onPress={onPress} style={({ pressed }) => [{ minHeight: 48, borderRadius: 14, paddingVertical: 11, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, backgroundColor: variant === 'primary' ? colors.hero : variant === 'secondary' ? colors.soft : 'transparent', borderWidth: isOutline ? 1 : 0, borderColor: variant === 'danger' ? colors.danger : colors.border, opacity: disabled || loading ? 0.5 : pressed ? 0.72 : 1, minWidth: 0, flexShrink: 1 }, style]}>{loading ? <ActivityIndicator color={color} /> : icon ? <Icon name={icon} color={color} size={18} /> : null}<Text style={{ color, fontSize: 14, lineHeight: 18, fontFamily: 'Manrope_600SemiBold', flexShrink: 1, textAlign: 'center' }}>{title}</Text></Pressable>;
}
export function IconButton({ name, label, onPress, active = false }: { name: IconName; label: string; onPress: () => void; active?: boolean }) { const { colors } = useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ selected: active }} onPress={onPress} style={({ pressed }) => ({ width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: active ? colors.tint : colors.soft, borderWidth: 1, borderColor: active ? colors.accent : colors.border, opacity: pressed ? 0.6 : 1, transform: [{ scale: pressed ? 0.94 : 1 }] })}><Icon name={name} color={active ? colors.accent : colors.text} size={19} /></Pressable>; }
export function ScreenHeader({ title, eyebrow, back = false, action }: { title: string; eyebrow?: string; back?: boolean; action?: React.ReactNode }) {
  const { colors } = useTheme(); const pathname = usePathname(); const languageAction = pathname !== '/language' ? <IconButton name="globe" label="Язык приложения" onPress={() => router.push('/language')} /> : null; const actions = action || languageAction ? <Row style={{ flexWrap: 'nowrap', gap: 6 }}>{action}{languageAction}</Row> : null; return <Row style={{ justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'nowrap', marginBottom: 8 }}>{back ? <IconButton name="arrow-left" label="Назад" onPress={() => router.canGoBack() ? router.back() : router.replace('/home')} /> : null}<View style={{ flex: 1, minWidth: 0 }}>{eyebrow ? <Text variant="label" color={colors.accent} style={{ marginBottom: 5 }}>{eyebrow}</Text> : null}<Text variant="title" style={{ flexShrink: 1 }}>{title}</Text></View>{actions}</Row>;
}
export function SectionHeader({ title, action, onPress }: { title: string; action?: string; onPress?: () => void }) { const { colors } = useTheme(); return <Row style={{ justifyContent: 'space-between', marginTop: 12 }}><Text variant="heading" style={{ flex: 1 }}>{title}</Text>{action && onPress ? <Pressable onPress={onPress} accessibilityRole="button" style={{ minHeight: 44, justifyContent: 'center' }}><Text color={colors.accent}>{action} →</Text></Pressable> : null}</Row>; }
export function Breadcrumbs({ items }: { items: { label: string; onPress?: () => void }[] }) { const { colors } = useTheme(); return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 6, alignItems: 'center' }}>{items.map((item, index) => <View key={`${item.label}-${index}`} style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>{index ? <Text variant="caption" color={colors.muted}>/</Text> : null}<Pressable disabled={!item.onPress} onPress={item.onPress} accessibilityRole={item.onPress ? 'button' : undefined}><Text variant="caption" color={item.onPress ? colors.accent : colors.muted}>{item.label}</Text></Pressable></View>)}</ScrollView>; }
export function Field({ label, error, ...props }: ComponentProps<typeof NativeInput> & { label: string; error?: string }) { const { colors, font } = useTheme(); return <View style={{ gap: 7 }}><Text variant="caption">{label}</Text><NativeInput {...props} accessibilityLabel={label} placeholderTextColor={colors.muted} style={[{ backgroundColor: colors.surface, borderColor: error ? colors.danger : colors.border, borderWidth: 1, borderRadius: 12, color: colors.text, fontFamily: font.body, minHeight: 52, paddingHorizontal: 15, paddingVertical: 13, fontSize: 16, ...(props.multiline ? { minHeight: 112, textAlignVertical: 'top' as const } : {}) }, props.style]} />{error ? <Text variant="caption" color={colors.danger} accessibilityRole="alert">{error}</Text> : null}</View>; }
export function SearchInput({ value, onChangeText, placeholder }: { value: string; onChangeText: (s: string) => void; placeholder?: string }) { const { t } = useI18n(); return <Field label={t('search')} placeholder={placeholder ?? t('searchPlaceholder')} value={value} onChangeText={onChangeText} returnKeyType="search" autoCapitalize="none" />; }
export function Chip({ label, selected, onPress }: { label: string; selected?: boolean; onPress: () => void }) { const { colors } = useTheme(); return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={{ minHeight: 42, justifyContent: 'center', borderWidth: 1, borderColor: selected ? colors.accent : colors.border, borderRadius: 24, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: selected ? colors.tint : colors.surface, maxWidth: '100%' }}><Text style={{ fontSize: 13, flexShrink: 1 }} color={selected ? colors.accent : colors.text}>{label}</Text></Pressable>; }
export function Badge({ label }: { label: string }) { const { colors } = useTheme(); return <View style={{ alignSelf: 'flex-start', maxWidth: '100%', borderRadius: 7, backgroundColor: colors.tint, paddingHorizontal: 8, paddingVertical: 4 }}><Text variant="caption" color={colors.accent} style={{ flexShrink: 1 }}>{label}</Text></View>; }
export function EmptyState({ title, description, icon = 'archive', action, onPress }: { title: string; description: string; icon?: IconName; action?: string; onPress?: () => void }) { const { colors } = useTheme(); return <Card style={{ alignItems: 'center', paddingVertical: 32 }}><View style={{ backgroundColor: colors.tint, padding: 20, borderRadius: 40, marginBottom: 4 }}><Icon name={icon} color={colors.accent} size={28} /></View><Text variant="heading" style={{ textAlign: 'center' }}>{title}</Text><Text color={colors.muted} style={{ textAlign: 'center', maxWidth: 350 }}>{description}</Text>{action && onPress ? <Button title={action} onPress={onPress} /> : null}</Card>; }
export function ErrorState({ error, retry }: { error: unknown; retry: () => void }) { const { t } = useI18n(); return <EmptyState icon="wifi-off" title={t('loadError')} description={errorMessage(error)} action={t('retry')} onPress={retry} />; }
export function LoadingSkeleton() { const { colors } = useTheme(); const { t } = useI18n(); return <Card><ActivityIndicator color={colors.accent} accessibilityLabel={t('loading')} /><View style={{ height: 100, borderRadius: 12, backgroundColor: colors.soft }} /><View style={{ height: 15, width: '70%', backgroundColor: colors.soft, borderRadius: 5 }} /><Text variant="caption" color={colors.muted}>{t('loading')}</Text></Card>; }
export function InlineError({ error }: { error: unknown }) { const { colors } = useTheme(); return error ? <Text accessibilityRole="alert" color={colors.danger}>{errorMessage(error)}</Text> : null; }
export function BottomSheet({ open, onClose, title, children }: PropsWithChildren<{ open: boolean; onClose: () => void; title: string }>) { const { colors } = useTheme(); return <NativeModal visible={open} transparent animationType="slide" onRequestClose={onClose}><View style={{ flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000066' }}><Pressable accessibilityLabel="Закрыть" onPress={onClose} style={StyleSheet.absoluteFill} /><SafeAreaView style={{ maxHeight: '90%', width: '100%', maxWidth: 700, alignSelf: 'center', backgroundColor: colors.background, borderTopLeftRadius: 28, borderTopRightRadius: 28 }}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 24, gap: 18 }}><Row style={{ justifyContent: 'space-between' }}><Text variant="heading">{title}</Text><IconButton name="x" label="Закрыть" onPress={onClose} /></Row>{children}</ScrollView></SafeAreaView></View></NativeModal>; }
export function LinkButton({ href, title, variant = 'secondary', icon }: { href: Href; title: string; variant?: 'primary' | 'secondary' | 'outline' | 'ghost'; icon?: IconName }) { return <Button title={title} variant={variant} icon={icon} onPress={() => router.push(href)} />; }
export function SegmentedControl({ options, value, onChange }: { options: { id: string; label: string }[]; value: string; onChange: (id: string) => void }) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{options.map(o => <Chip key={o.id} label={o.label} selected={value === o.id} onPress={() => onChange(o.id)} />)}</ScrollView>; }
export const Tabs = SegmentedControl;
export const Modal = BottomSheet;
export function Avatar({ name }: { name: string }) { const { colors } = useTheme(); return <View style={{ width: 60, height: 60, borderRadius: 30, backgroundColor: colors.tint, alignItems: 'center', justifyContent: 'center' }}><Text variant="heading" color={colors.accent}>{name.slice(0, 2).toUpperCase()}</Text></View>; }
const styles = StyleSheet.create({ content: { width: '100%', maxWidth: 960, alignSelf: 'center', paddingHorizontal: 16, paddingTop: 14, paddingBottom: 30, gap: 16 }, row: { flexDirection: 'row', alignItems: 'center', gap: 10, flexWrap: 'wrap' } });
