import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { catalogApi } from '../../shared/api/services';
import type { ItemFilters } from '../../entities/types';
import { BottomSheet, Button, Chip, Field, InlineError, Row, Text } from '../../shared/ui/core';
export function FilterSheet({ open, onClose, value, onApply, marketplace = false }: { open: boolean; onClose: () => void; value: ItemFilters; onApply: (v: ItemFilters) => void; marketplace?: boolean }) {
  const [draft, setDraft] = useState(value);
  const categories = useQuery({ queryKey: ['categories'], queryFn: ({ signal }) => catalogApi.categories(signal), enabled: open });
  const fields: { key: keyof ItemFilters; label: string }[] = [{ key: 'yearFrom', label: 'Год от' }, { key: 'yearTo', label: 'Год до' }, { key: 'country', label: 'Страна' }, { key: 'material', label: 'Материал' }, ...(marketplace ? [{ key: 'fineness' as const, label: 'Проба' }, { key: 'weightMin' as const, label: 'Вес от, г' }, { key: 'weightMax' as const, label: 'Вес до, г' }, { key: 'priceMin' as const, label: 'Цена от' }, { key: 'priceMax' as const, label: 'Цена до' }, { key: 'form' as const, label: 'Форма: слиток, монета, украшение…' }, { key: 'manufacturer' as const, label: 'Производитель' }] : [])];
  return <BottomSheet open={open} onClose={onClose} title="Настроить поиск"><Text color="#617783">Выберите параметры, чтобы быстрее найти подходящий предмет.</Text><Text variant="label">Категории</Text><InlineError error={categories.error} /><Row style={{ flexWrap: 'wrap' }}><Chip label="Все" selected={!draft.categoryId} onPress={() => setDraft({ ...draft, categoryId: undefined })} />{categories.data?.map(c => <Chip key={c.id} label={c.name} selected={draft.categoryId === c.id} onPress={() => setDraft({ ...draft, categoryId: c.id })} />)}</Row>{marketplace ? <Row><Chip label="Золото" selected={draft.metal === 'gold'} onPress={() => setDraft({ ...draft, metal: draft.metal === 'gold' ? undefined : 'gold' })} /><Chip label="Серебро" selected={draft.metal === 'silver'} onPress={() => setDraft({ ...draft, metal: draft.metal === 'silver' ? undefined : 'silver' })} /></Row> : <Chip label="Только избранное" selected={draft.favorite} onPress={() => setDraft({ ...draft, favorite: !draft.favorite })} />}{fields.map(f => <Field key={f.key} label={f.label} value={String(draft[f.key] ?? '')} onChangeText={v => setDraft({ ...draft, [f.key]: v || undefined })} />)}<Row style={{ flexWrap: 'wrap' }}><Chip label="Сначала новые" selected={draft.sort !== 'oldest'} onPress={() => setDraft({ ...draft, sort: 'recent' })} /><Chip label="Сначала старые" selected={draft.sort === 'oldest'} onPress={() => setDraft({ ...draft, sort: 'oldest' })} /></Row><Button title="Показать результаты" onPress={() => { onApply(draft); onClose(); }} /><Button title="Сбросить фильтры" variant="ghost" onPress={() => { setDraft({}); onApply({}); onClose(); }} /></BottomSheet>;
}
